"""One-shot Skool login → cookies.txt helper.

You run this, paste your Skool email + password at the prompts, and the
script logs in with a real Chromium (Playwright) and writes a Netscape
cookies.txt to ``./cookies/skool.txt`` for the crawler to use.

What this script does:

    1. Opens https://www.skool.com/login
    2. You type your email + password at the two prompts
    3. Optionally clicks through 2FA / email verification if Skool shows it
    4. Dumps every cookie the browser holds for skool.com to cookies.txt

What this script does *not* do:

    * Save your password anywhere
    * Send your credentials anywhere except skool.com
    * Persist the Playwright profile on disk (a fresh ephemeral profile is
      used and discarded)
    * Read your keychain (no Keychain access at all)

Dependencies: ``playwright`` and the chromium browser binary it ships with.
Install with::

    .venv/bin/pip install playwright
    .venv/bin/playwright install chromium
"""
from __future__ import annotations

import getpass
import sys
from pathlib import Path

COOKIES_OUT = Path(__file__).resolve().parents[1] / "cookies" / "skool.txt"
SKOOL_DOMAINS = {"skool.com", ".skool.com"}


def main() -> int:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print(
            "playwright is not installed in this venv.\n"
            "Run:\n"
            "    .venv/bin/pip install playwright\n"
            "    .venv/bin/playwright install chromium\n"
            "then re-run this script.",
            file=sys.stderr,
        )
        return 2

    print("Skool login → cookies.txt helper")
    print("=" * 40)
    print("This will open a real browser window to https://www.skool.com/login.")
    print("Your password is typed into the Skool login form and is NOT saved")
    print("to disk by this script. The Playwright profile is ephemeral.")
    print()
    email = input("Skool email: ").strip()
    if not email:
        print("email is required", file=sys.stderr)
        return 2
    password = getpass.getpass("Skool password: ")
    if not password:
        print("password is required", file=sys.stderr)
        return 2

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        try:
            ctx = browser.new_context()
            page = ctx.new_page()
            page.goto("https://www.skool.com/login", timeout=30000)
            # Skool's login form uses email + password fields; the selectors
            # below are what their frontend renders as of late 2024.
            try:
                page.fill('input[type="email"]', email)
                page.fill('input[type="password"]', password)
            except Exception as exc:
                print(
                    f"couldn't find login form fields: {exc}\n"
                    "The Skool login page may have changed. Open the browser\n"
                    "window, log in manually, then re-run this script with\n"
                    "the --manual flag (if implemented) or follow the README.",
                    file=sys.stderr,
                )
                return 3
            page.click('button[type="submit"]')
            # Give Skool time to show 2FA / email verification / a redirect.
            print("\nIf Skool shows 2FA or email verification, complete it")
            print("in the browser window, then come back here and press Enter.")
            input("Press Enter once you're fully logged in (or Ctrl-C to abort)...")
            # Confirm we're actually past the login wall.
            current_url = page.url
            if "/login" in current_url or "/about" in current_url and "join" in current_url:
                print(
                    f"warning: current page is still {current_url!r}.\n"
                    "cookies may be incomplete. Continuing anyway.",
                    file=sys.stderr,
                )

            cookies = ctx.cookies()
            skool_cookies = [c for c in cookies if _is_skool(c.get("domain", ""))]
            if not skool_cookies:
                print("no skool.com cookies found in the browser session.", file=sys.stderr)
                return 4

            _write_netscape(skool_cookies, COOKIES_OUT)
            print(f"\nwrote {len(skool_cookies)} cookies to {COOKIES_OUT}")
        finally:
            browser.close()
    return 0


def _is_skool(domain: str) -> bool:
    d = domain.lower().lstrip(".")
    return d == "skool.com" or d.endswith(".skool.com")


def _write_netscape(cookies: list[dict], out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# generated by skool_ingest/scripts/skool_login.py", ""]
    for c in cookies:
        domain = c.get("domain", "")
        # Netscape expects the leading dot for domain cookies; we preserve it.
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        # HTTP-only cookies (skool_session is one) have expires=-1, which is
        # a session cookie. Netscape uses 0 for that.
        expires = c.get("expires", 0)
        if expires is None or expires < 0:
            expires = 0
        name = c.get("name", "")
        value = c.get("value", "")
        # domain includeSubDomains flag
        # Netscape: a leading dot in the domain column means include subdomains.
        # Playwright's "sameSite" / "hostOnly" are unrelated; we ignore them.
        lines.append(f"{domain}\tTRUE\t{path}\t{secure}\t{int(expires)}\t{name}\t{value}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
